"""empty message

Revision ID: 71b94f5cd679
Revises: e364329a0b88
Create Date: 2024-04-11 19:06:12.351985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b94f5cd679'
down_revision = 'e364329a0b88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_page')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('about_me', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('prof_pic_url', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('prof_pic_url')
        batch_op.drop_column('about_me')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    op.create_table('user_page',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('about_me', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('prof_pic_url', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('top_artists', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('top_genres', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], name='user_page_uid_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_page_pkey')
    )
    # ### end Alembic commands ###
