"""empty message

Revision ID: 755f31aecf20
Revises: 45fccceff731
Create Date: 2024-04-04 14:44:09.600798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755f31aecf20'
down_revision = '45fccceff731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_genre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('count', sa.Integer(), nullable=True))
        batch_op.drop_column('genre_tracked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_genre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_tracked', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('count')
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
