"""empty message

Revision ID: aea234538a64
Revises: f0dbe8f02681
Create Date: 2024-04-02 19:21:30.011062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea234538a64'
down_revision = 'f0dbe8f02681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('artist', sa.String(length=120), nullable=True),
    sa.Column('venue', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('date', sa.String(length=120), nullable=True),
    sa.Column('img_url', sa.String(length=120), nullable=True),
    sa.Column('attended_with', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recieved_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recieved_id'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('playlist_name', sa.String(length=120), nullable=False),
    sa.Column('top_three', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=250), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('top_songs', sa.String(length=250), nullable=True),
    sa.Column('top_artists', sa.String(length=250), nullable=True),
    sa.Column('top_genres', sa.String(length=250), nullable=True),
    sa.Column('attended_concerts', sa.String(length=250), nullable=True),
    sa.Column('upcoming_concerts', sa.String(length=250), nullable=True),
    sa.Column('about_me', sa.String(length=250), nullable=True),
    sa.Column('prof_pic_url', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('comment_text', sa.String(length=250), nullable=True),
    sa.Column('postid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['postid'], ['post.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist_songs',
    sa.Column('psid', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('song_name', sa.String(length=120), nullable=True),
    sa.Column('song_genre', sa.String(length=120), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['playlist.pid'], ),
    sa.PrimaryKeyConstraint('psid')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('dob', sa.String(length=120), nullable=False))
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.drop_column('dob')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('uid')

    op.drop_table('playlist_songs')
    op.drop_table('comment')
    op.drop_table('user_page')
    op.drop_table('post')
    op.drop_table('playlist')
    op.drop_table('inbox')
    op.drop_table('follower')
    op.drop_table('event')
    # ### end Alembic commands ###
